targets:
  - name: Randstad
    ats: smartrecruiters
    smartrecruiters_slugs: ["Randstad4", "randstad", "randstad-emea"]
    smartrecruiters_countries: ["Italy"]

  - name: Universal Music Group
    ats: workday
    workday_tenant: umusic
    # Try preferred first, but we will rotate through all below if needed
    workday_host: umusic.wd5.myworkdayjobs.com
    workday_hosts:
      - umusic.wd5.myworkdayjobs.com
      - umusic.wd3.myworkdayjobs.com
      - umusic.wd2.myworkdayjobs.com
      - umusic.wd1.myworkdayjobs.com
    workday_sites: ["UMGUS", "UMGUK", "universal-music-group", "UNIVERSAL-MUSIC-GROUP", "Global", "External", "Careers", "Jobs"]

  - name: Warner Music Group
    ats: workday
    workday_tenant: wmg
    workday_host: wmg.wd1.myworkdayjobs.com
    workday_hosts:
      - wmg.wd1.myworkdayjobs.com
      - wmg.wd3.myworkdayjobs.com
      - wmg.wd2.myworkdayjobs.com
      - wmg.wd5.myworkdayjobs.com
    workday_sites: ["WMGUS", "WMGGLOBAL", "WMG", "Wmg", "Global", "External", "Careers", "Jobs"]

  # Keep Adecco (Italy) custom scraper below, unchanged:
  # - name: Adecco (Italy)
  #   ats: custom
  #   target: adecco_it
