# config/companies.yml
# Master list of sources the aggregator will query.
# Every entry under `targets:` is one source with an `ats` adapter.

targets:
  # --- Randstad via SmartRecruiters (global feed, then we filter by country) ---
  - name: "Randstad (SmartRecruiters)"
    ats: smartrecruiters
    smartrecruiters_slugs:
      - "randstad"
      - "randstaditaly"
      - "randstad-italia"
      - "randstaditalia"
      - "randstad-emea"
      - "Randstad4"
    smartrecruiters_countries: ["Italy"]

  # --- Randstad Italy site scraper (backup to SR feed) ---
  - name: "Randstad (Italy)"
    ats: randstad_it
    country: "IT"

  # --- Adecco Italy site scraper (backup to SR) ---
  - name: "Adecco (Italy)"
    ats: adecco_it
    country: "IT"

  # --- Universal Music Group (Workday via Playwright) ---
  - name: "Universal Music Group"
    ats: workday_pw
    workday_hosts:
      - "umusic.wd5.myworkdayjobs.com"
      - "umusic.wd1.myworkdayjobs.com"   # fallback
    workday_sites:
      - "UMGUS"
      - "UMGUK"
      - "External"
    label: "UMG"

  # --- Warner Music Group (Workday via Playwright) ---
  - name: "Warner Music Group"
    ats: workday_pw
    workday_hosts:
      - "wmg.wd1.myworkdayjobs.com"
    workday_sites:
      - "WMGUS"
      - "WMGGLOBAL"
      - "External"
    label: "WMG"
