targets:
  - name: Randstad
    ats: smartrecruiters
    smartrecruiters_slugs: ["randstad","randstaditaly","randstad-italia","randstaditalia","randstad-emea","Randstad4"]
    smartrecruiters_countries: ["Italy"]

  - name: Universal Music Group
    ats: workday_gql
    workday_tenant: umusic
    workday_host: umusic.wd5.myworkdayjobs.com
    workday_sites: ["UMGUS","UMGUK","External","Global"]

  - name: Warner Music Group
    ats: workday_gql
    workday_tenant: wmg
    workday_host: wmg.wd1.myworkdayjobs.com
    workday_sites: ["WMGUS","WMGGLOBAL","External","Global"]
