targets:
  - name: Randstad
    ats: randstad_it
    base_url: "https://www.randstad.it/offerte-lavoro"
    query: ""
    max_pages: 5
    pause_s: 0.8
    debug: false

  - name: Adecco
    ats: adecco_it
    base_url: "https://www.adecco.it/offerte-lavoro"
    query: ""
    max_pages: 5
    pause_s: 0.8
    debug: false

  - name: Universal Music Group
    ats: workday_pw_gql
    workday_pw_hosts:
      - umusic.wd5.myworkdayjobs.com
    workday_pw_sites:
      - UMGUS
      - UMGUK
      - External

  - name: Warner Music Group
    ats: workday_pw_gql
    workday_pw_hosts:
      - wmg.wd1.myworkdayjobs.com
    workday_pw_sites:
      - WMGUS
      - WMGGLOBAL
      - External