schedule:
  run_hour_local: 9

targets:
  # --- CORE DSPs / PLATFORMS ---
  - name: Spotify
    ats: lever
    slug: spotify

  - name: Apple Music
    ats: rss
    homepage: https://www.apple.com/careers/us/
    rss: https://www.apple.com/newsroom/rss-feed.rss

  - name: YouTube Music / Google
    ats: rss
    homepage: https://careers.google.com/
    rss: https://careers.google.com/jobs/results/feed/rss/

  - name: Amazon Music
    ats: rss
    homepage: https://www.amazon.jobs/
    rss: https://www.amazon.jobs/en/rss

  - name: Meta (Facebook/Instagram)
    ats: rss
    homepage: https://www.metacareers.com/
    rss: https://www.metacareers.com/jobs/feed

  - name: TikTok / ByteDance (Music)
    ats: rss
    homepage: https://careers.tiktok.com/

  - name: Deezer
    ats: rss
    homepage: https://www.deezerjobs.com/

  - name: SoundCloud
    ats: greenhouse
    slug: soundcloud71

  - name: TIDAL (Block)
    ats: rss
    homepage: https://block.xyz/careers/

  # --- MAJORS / LABEL GROUPS ---
  - name: Sony Music
    ats: greenhouse
    slug: sonymusic

  - name: Universal Music Group
    ats: workday_gql
    slug: universal-music-group
    workday_host: umusic
    workday_tenant: wd5
    workday_sites: ["UMGUS","UMGUK"]

  - name: Warner Music Group
    ats: rss
    homepage: https://www.wmg.com/careers

  - name: The Orchard (Sony)
    ats: rss
    homepage: https://www.theorchard.com/company/careers/

  - name: AWAL (Sony)
    ats: rss
    homepage: https://www.awal.com/careers/

  - name: Virgin Music Group (UMG)
    ats: rss
    homepage: https://www.virgin.com/careers

  - name: Ingrooves (UMG)
    ats: rss
    homepage: https://www.ingrooves.com/careers/

  # --- DISTRIBUTORS / RIGHTS TECH ---
  - name: Believe
    ats: rss
    homepage: https://careers.believe.com/en/

  - name: DistroKid
    ats: rss
    homepage: https://distrokid.com/jobs

  - name: TuneCore
    ats: rss
    homepage: https://www.tunecore.com/company/careers

  - name: CD Baby
    ats: rss
    homepage: https://cdbaby.com/

  - name: Merlin Network
    ats: rss
    homepage: https://www.merlinnetwork.org/careers

  - name: Jaxsta
    ats: rss
    homepage: https://www.jaxsta.com/company/careers

  - name: Muso.ai
    ats: rss
    homepage: https://muso.ai/careers

  # --- LYRICS / METADATA ---
  - name: Musixmatch
    ats: lever
    slug: musixmatch

  - name: LyricFind
    ats: rss
    homepage: https://www.lyricfind.com/

  # --- CREATOR TOOLS / DAWs / AUDIO TECH ---
  - name: Ableton
    ats: rss
    homepage: https://www.ableton.com/en/jobs/

  - name: Native Instruments
    ats: rss
    homepage: https://www.native-instruments.com/company/jobs/

  - name: Avid
    ats: rss
    homepage: https://www.avid.com/company/careers

  - name: BandLab
    ats: rss
    homepage: https://bandlab.com/careers

  - name: LANDR
    ats: rss
    homepage: https://www.landr.com/careers

  - name: Dolby
    ats: rss
    homepage: https://careers.dolby.com/

  - name: Audacity
    ats: rss
    homepage: https://www.audacityteam.org/

  - name: iZotope (Soundwide/NI)
    ats: rss
    homepage: https://www.izotope.com/en/careers.html

  - name: Focusrite / Novation
    ats: rss
    homepage: https://focusriteplc.com/careers

  # --- NOTATION / SCORING / EDUCATION ---
  - name: MuseScore
    ats: rss
    homepage: https://www.mu.se/careers

  - name: Noteflight (Hal Leonard)
    ats: rss
    homepage: https://www.noteflight.com/jobs

  - name: Flat.io
    ats: rss
    homepage: https://flat.io/en/careers

  - name: StaffPad
    ats: rss
    homepage: https://www.staffpad.net/

  - name: Soundslice
    ats: rss
    homepage: https://www.soundslice.com/jobs/

  # --- AI MUSIC / VOICE TECH ---
  - name: ElevenLabs
    ats: ashby
    slug: elevenlabs

  - name: AIVA
    ats: rss
    homepage: https://www.aiva.ai/careers

  - name: Endel
    ats: rss
    homepage: https://endel.io/careers

  - name: AudioShake
    ats: rss
    homepage: https://www.audioshake.ai/

  - name: Boomy
    ats: rss
    homepage: https://www.boomy.com/careers

  - name: Soundful
    ats: rss
    homepage: https://www.soundful.com/

  # --- SYNC / PRODUCTION MUSIC / LIBRARIES ---
  - name: Epidemic Sound
    ats: rss
    homepage: https://www.epidemicsound.com/careers/

  - name: Audio Network
    ats: rss
    homepage: https://www.audionetwork.com/careers

  - name: Universal Production Music
    ats: rss
    homepage: https://www.universalproductionmusic.com/en-it/about/careers

  # --- ITALY-FOCUSED & VENDORS ---
  - name: Accenture (Italy)
    ats: workday_gql
    slug: accenture
    workday_host: accenture
    workday_tenant: wd103
    workday_sites: ["AccentureCareers"]

  - name: Reply (Italy)
    ats: rss
    homepage: https://www.reply.com/en/about/careers

  - name: Gi Group
    ats: rss
    homepage: https://www.gigroupholding.com/careers/

  - name: Randstad
    ats: smartrecruiters
    smartrecruiters_slugs: ["randstad", "randstaditaly", "randstad-italia", "randstaditalia", "randstad-emea", "Randstad4"]
    smartrecruiters_countries: ["Italy"]   # country-only (OR logic) for first pass

  - name: Adecco
    ats: smartrecruiters
    smartrecruiters_slugs: ["adeccoitaly", "adecco-italy", "adeccoitalia", "adecco", "adeccogroup", "adeccoireland", "adecco-uk", "AdeccoStaffingUSA1"]
    smartrecruiters_countries: ["Italy","Ireland","United Kingdom","Germany","Spain","France","Netherlands","Portugal","Switzerland","Austria","Belgium","Luxembourg","Poland","Czechia","Romania"]

  - name: ManpowerGroup
    ats: rss
    homepage: https://www.manpowergroup.com/work-with-us

  - name: SIAE (Italian PRO)
    ats: rss
    homepage: https://www.siae.it/

  - name: FIMI (Italy)
    ats: rss
    homepage: https://www.fimi.it/

  - name: Sugar Music (Italy)
    ats: rss
    homepage: https://www.sugarmusic.com/

  # --- OTHER GOOD SIGNAL COMPANIES ---
  - name: Shazam (Apple)
    ats: rss
    homepage: https://www.shazam.com/

  - name: Bandcamp
    ats: rss
    homepage: https://bandcamp.com/jobs

  - name: Discogs
    ats: rss
    homepage: https://careers.discogs.com/

  - name: Beatport
    ats: rss
    homepage: https://www.beatport.com/

  - name: Mixcloud
    ats: rss
    homepage: https://www.mixcloud.com/careers/

  - name: TuneIn
    ats: rss
    homepage: https://tunein.com/careers/

  - name: Audible (Amazon)
    ats: rss
    homepage: https://www.audiblecareers.com/

  - name: Pandora / SiriusXM
    ats: rss
    homepage: https://www.siriusxm.com/careers

  - name: Sonos
    ats: rss
    homepage: https://www.sonos.com/en-us/careers
